// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhphmccOpcOOwy97Wz_KqYizK4WVJobn8',
    appId: '1:695905499763:web:cf259e90cc0896157f8806',
    messagingSenderId: '695905499763',
    projectId: 'act14app',
    authDomain: 'act14app.firebaseapp.com',
    storageBucket: 'act14app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqxWXCrOwIs5pJmagCTsTVZOIkNVAaVcw',
    appId: '1:695905499763:android:7c49ca64ad05ef977f8806',
    messagingSenderId: '695905499763',
    projectId: 'act14app',
    storageBucket: 'act14app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFve3PgxIjJZVMsK2xAymss1n6OS0bc9s',
    appId: '1:695905499763:ios:cd605cd17eaf8ae87f8806',
    messagingSenderId: '695905499763',
    projectId: 'act14app',
    storageBucket: 'act14app.firebasestorage.app',
    iosBundleId: 'com.example.act14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFve3PgxIjJZVMsK2xAymss1n6OS0bc9s',
    appId: '1:695905499763:ios:cd605cd17eaf8ae87f8806',
    messagingSenderId: '695905499763',
    projectId: 'act14app',
    storageBucket: 'act14app.firebasestorage.app',
    iosBundleId: 'com.example.act14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhphmccOpcOOwy97Wz_KqYizK4WVJobn8',
    appId: '1:695905499763:web:c5ec0f07a9071daa7f8806',
    messagingSenderId: '695905499763',
    projectId: 'act14app',
    authDomain: 'act14app.firebaseapp.com',
    storageBucket: 'act14app.firebasestorage.app',
  );
}
